name: Update Lambda Code

on:
  push:
    paths:
      - 'node-project/**'
  pull_request:
    paths:
      - 'node-project/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: node-project

      - name: Run tests
        run: npm test
        working-directory: node-project
