name: PR Event Handler

on:
  pull_request:
    #types: [opened, synchronize, reopened, closed, edited, ready_for_review, labeled, unlabeled]
    paths:
      - 'lambdas/nodejs/**'
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      
      - name: Find Node.js projects with code updates
        id: find_updated_nodejs_projects
        run: |
          # Find all directories with package.json that have changed src files
          # Step 1. Find all the updated projects in lambdas directory through diff
          projects=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep '^lambdas/nodejs/[^/]\+/src/' | cut -d'/' -f2 | uniq)
          echo "projects=$projects" >> $GITHUB_ENV

      - name: Lint Node.js projects
        if: env.projects
        run: |
          for project in ${{ env.projects }}; do
            echo "Setting up Node.js for lambdas/nodejs/$project"
            cd lambdas/nodejs/$project

            npm run lint
            cd -
          done
