name: PR Event Handler

on:
  pull_request:
    #types: [opened, synchronize, reopened, closed, edited, ready_for_review, labeled, unlabeled]
    paths:
      - 'lambdas/nodejs/**'
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Node.js updated projects
        id: find_updated_nodejs_projects
        run: |
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          HEAD_REF="${{ github.event.pull_request.head.ref }}"
          echo "BASE_REF: $BASE_REF"
          echo "HEAD_REF: $HEAD_REF"
          
          git fetch origin $BASE_REF $HEAD_REF
          
          projects=$(git diff --name-only origin/$BASE_REF origin/$HEAD_REF | grep '^lambdas/nodejs/[^/]\+' | cut -d'/' -f3 | uniq | tr '\n' ' ')
          echo "projects=$projects" >> $GITHUB_ENV

      - name: Print projects
        run: |
          echo "Projects with diffs: ${{ env.projects }}"
          
      - name: Lint Node.js projects
        if: env.projects != ''
        run: |
          for project in ${{ env.projects }}; do
            echo "Setting up Node.js for lambdas/nodejs/$project"
            cd lambdas/nodejs/$project
            npm i
            npm run lint
            cd -
          done
